name: Deploy to Rasberry Pi 5

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64, rasberry-pi]

    steps:
      - name: Deploy on Raspberry Pi
        run: |
          cd ~/owoon-was
          ./scripts/deploy.sh